### ISSUE TITLE
Commit thiếu trong Application

### ISSUE THREAD

**Issue by maiquocson** [teduinternational/eShopSolution#14]
Anh ơi , anh commit thiếu mấy cái folder Dtos rồi.
![Snag_2f875b](https://user-images.githubusercontent.com/26180126/100040866-aa97fb80-2e3a-11eb-970b-a2667ea8aded.png)

**Comment by teducolabs** [comment]
Ok em

**Comment by teducolabs** [comment]
a check lại thì không có folder dto đâu em
